import argparse

parser = argparse.ArgumentParser(description='DSS')
parser.add_argument('--feat-extractor', default='i3d', choices=['i3d', 'c3d', 'clip'])
parser.add_argument('--feature-size', type=int, default=1024, help='size of feature (default: 2048)')
parser.add_argument('--modality', default='RGB', help='the type of the input, RGB, AUDIO, or MIX')
parser.add_argument('--rgb-list', default='list/xd-train.list', help='list of rgb features ')
parser.add_argument('--test-rgb-list', default='list/xd-test.list', help='list of test rgb features ')
parser.add_argument('--gt', default='list/gt-xd.npy', help='file of ground truth ')
parser.add_argument('--gpus', default=1, type=int, choices=[0], help='gpus')
parser.add_argument('--lr', type=str, default='[0.0001]*20000', help='learning rates for steps(list form)')
parser.add_argument('--batch-size', type=int, default=16, help='number of instances in a batch of data (default: 16)')
parser.add_argument('--workers', default=4, help='number of workers in dataloader')
parser.add_argument('--model-name', default='DSS', help='name to save model')
parser.add_argument('--num-classes', type=int, default=1, help='number of class')
parser.add_argument('--dataset', default='xd', help='dataset to train on (default: xd)')
parser.add_argument('--plot-freq', type=int, default=10, help='frequency of plotting (default: 10)')
parser.add_argument('--max-epoch', type=int, default=20000, help='maximum iteration to train (default: 100)')
parser.add_argument('--mem-num', type=int, default=30, help='number of memory (default: 60)')
parser.add_argument('--mem-size', type=int, default=512, help='size of memory (default: 512)')